<?php
/**
 * Created S/09/02/2013
 * Updated M/23/08/2016
 * Version 19
 *
 * Copyright 2011-2016 | Fabrice Creuzot (luigifab) <code~luigifab~info>
 * https://redmine.luigifab.info/projects/magento/wiki/versioning
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

$lang = substr(Mage::getSingleton('core/locale')->getLocaleCode(), 0, 2);

?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $lang ?>" lang="<?php echo $lang ?>" style="height:100%;">
<head>
	<title><?php echo $this->__('Version control / Tools / Magento Admin'),' - ',Mage::getStoreConfig('design/head/default_title') ?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="Content-Script-Type" content="text/javascript" />
	<meta http-equiv="Content-Style-Type" content="text/css" />
	<meta http-equiv="Content-Language" content="<?php echo $lang ?>" />
	<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->getSkinUrl('reset.css') ?>" />
	<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->getSkinUrl('boxes.css') ?>" />
	<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->getSkinUrl('css/luigifab/versioning/styles.min.css') ?>" />
	<link rel="icon" type="image/x-icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" />
	<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/luigifab/versioning/app.min.js') ?>"></script>
</head>

<body class="adminhtml-versioning-repository-confirm">
	<form action="<?php echo $this->helper('adminhtml')->getUrl('*/*/upgrade', array('revision' => $this->getRequest()->getParam('revision'), 'confirm' => '1')) ?>" method="get" onsubmit="versioning.valid('<?php echo $this->__('Operation in progress...') ?>');">
		<h1 class="<?php echo Mage::getStoreConfig('versioning/scm/type') ?>"><?php echo $this->__('Update to revision %s', $this->getRequest()->getParam('revision')) ?></h1>
		<div class="bbcode">
			<?php echo $this->helper('versioning')->getFields() ?>
		</div>
		<div class="buttons">
			<button type="submit" autofocus="autofocus"><?php echo $this->__('Continue') ?></button>
			<button type="button" class="back" onclick="versioning.valid('<?php echo $this->helper('adminhtml')->getUrl('*/versioning_repository/index') ?>');"><?php echo $this->__('Cancel') ?></button>
		</div>
	</form>
	<p class="credits"><?php echo $this->__('Martian sunset seen by Spirit.') ?></p>
</body>
</html>