<?php
/**
 * Created S/20/02/2016
 * Updated J/18/04/2019
 *
 * Copyright 2011-2019 | Fabrice Creuzot (luigifab) <code~luigifab~fr>
 * https://www.luigifab.fr/magento/versioning
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

$cssjs = $this->helper('versioning')->getCssJsHtml();
$lang  = mb_substr(Mage::getSingleton('core/locale')->getLocaleCode(), 0, 2);

?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $lang ?>" lang="<?php echo $lang ?>" style="height:100%;">
<head>
	<title><?php echo $this->__('Log into Magento Admin Page'),' - ',Mage::getStoreConfig('design/head/default_title') ?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="Content-Script-Type" content="text/javascript" />
	<meta http-equiv="Content-Style-Type" content="text/css" />
	<meta http-equiv="Content-Language" content="<?php echo $lang ?>" />
	<meta name="robots" content="noindex,nofollow" />
	<?php if (is_string($cssjs)): ?>
		<?php echo $cssjs,"\n" ?>
		<link rel="icon" type="image/x-icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" />
	<?php else: ?>
		<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->getSkinUrl('reset.css') ?>" />
		<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->getSkinUrl('boxes.css') ?>" />
		<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->getSkinUrl('css/luigifab/versioning/styles.min.css') ?>" />
		<link rel="icon" type="image/x-icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" />
		<?php if (Mage::getStoreConfigFlag('admin/captcha/enable')): ?>
			<script type="text/javascript" src="<?php echo $this->getJsUrl('prototype/prototype.js') ?>"></script>
			<script type="text/javascript" src="<?php echo $this->getJsUrl('mage/captcha.js') ?>"></script>
		<?php endif ?>
	<?php endif ?>
</head>

<body id="page-login">
	<div class="login-container">
		<div class="login-box">
			<form method="post" action="">
				<div class="login-form">
					<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
					<h2><?php echo $this->__('Forgot your user name or password?') ?></h2>
					<div id="messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
					<div class="input-box forgot-password">
						<label for="email"><?php echo $this->__('Email Address:') ?></label>
						<br /><input type="text" name="email" class="required-entry input-text validate-email" id="email" spellcheck="false" required="required" autofocus="autofocus" style="width:461px;" />
					</div>
					<?php echo str_replace('class="required-entry', 'required="required"  class="required-entry', $this->getChildHtml('form.additional.info')) ?>
					<div class="clear"></div>
					<div class="form-buttons">
						<a href="<?php echo $this->getUrl('adminhtml', array('_nosecret' => true)) ?>" class="left"><?php echo $this->__('Back to Login') ?></a>
						<input type="submit" class="form-button" value="<?php echo $this->__('Retrieve Password') ?>" />
					</div>
				</div>
			</form>
			<div class="bottom"></div>
		</div>
	</div>
	<p class="credits"><?php echo $this->__('Martian sunset seen by Spirit.') ?></p>
</body>
</html>