<?php
/**
 * Created S/20/02/2016
 * Updated L/22/02/2016
 * Version 2
 *
 * Copyright 2011-2016 | Fabrice Creuzot (luigifab) <code~luigifab~info>
 * https://redmine.luigifab.info/projects/magento/wiki/versioning
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

$lang = substr(Mage::app()->getLocale()->getLocaleCode(), 0, 2);

?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $lang ?>" lang="<?php echo $lang ?>" style="height:100%;">
<head>
	<title><?php echo $this->helper('adminhtml')->__('Log into Magento Admin Page'),' - ',Mage::getStoreConfig('design/head/default_title') ?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="Content-Script-Type" content="text/javascript" />
	<meta http-equiv="Content-Style-Type" content="text/css" />
	<meta http-equiv="Content-Language" content="<?php echo $lang ?>" />
	<link rel="stylesheet" type="text/css" charset="utf-8" media="screen" href="<?php echo $this->getSkinUrl('reset.css') ?>" />
	<link rel="stylesheet" type="text/css" charset="utf-8" media="screen" href="<?php echo $this->getSkinUrl('boxes.css') ?>" />
	<link rel="stylesheet" type="text/css" charset="utf-8" media="screen" href="<?php echo $this->getSkinUrl('css/luigifab/versioning/styles.min.css') ?>" />
	<link rel="icon" type="image/x-icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" />
	<script type="text/javascript" src="<?php echo $this->getJsUrl('prototype/prototype.js') ?>"></script>
	<script type="text/javascript" src="<?php echo $this->getJsUrl('prototype/validation.js') ?>"></script>
	<script type="text/javascript" src="<?php echo $this->getJsUrl('mage/adminhtml/form.js') ?>"></script>
	<script type="text/javascript" src="<?php echo $this->getJsUrl('mage/captcha.js') ?>"></script>
</head>

<body id="page-login" onload="document.getElementById('email').focus();">
	<div class="login-container">
		<div class="login-box">
			<form method="post" action="" id="loginForm">
				<div class="login-form">
					<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
					<h2><?php echo $this->helper('adminhtml')->__('Forgot your user name or password?') ?></h2>
					<div id="messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
					<div class="input-box forgot-password">
						<label for="email"><?php echo $this->helper('adminhtml')->__('Email Address:') ?></label>
						<br /><input type="text" name="email" class="required-entry input-text validate-email" id="email" style="width:461px;" />
					</div>
					<?php echo $this->getChildHtml('form.additional.info') ?>
					<div class="clear"></div>
					<div class="form-buttons">
						<a href="<?php echo $this->getUrl('adminhtml', array('_nosecret' => true)) ?>" class="left"><?php echo $this->helper('adminhtml')->__('Back to Login') ?></a>
						<input type="submit" class="form-button" value="<?php echo $this->helper('adminhtml')->__('Retrieve Password') ?>" />
					</div>
				</div>
				<p class="legal"><?php echo $this->helper('adminhtml')->__('Magento is a trademark of Magento Inc. Copyright &copy; %s Magento Inc.', date('Y')) ?></p>
			</form>
			<div class="bottom"></div>
			<script type="text/javascript">
			var loginForm = new varienForm('loginForm');
			</script>
		</div>
	</div>
	<p class="credits"><?php echo $this->__('Martian sunset by Spirit.') ?></p>
</body>
</html>