<?php
/**
 * Created W/30/05/2012
 * Updated D/03/06/2012
 * Version 5
 *
 * Copyright 2012-2013 | Fabrice Creuzot (luigifab) <code~luigifab~info>
 * https://redmine.luigifab.info/projects/magento/wiki/versioning
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */
?>

<div class="box error404">
	<div class="number"><span>4</span><span>0</span><span>4</span></div>
	<h1><?php echo $this->overload->translate('error404_title') ?></h1>
	<?php echo $this->overload->translate('error404_content') ?>
</div>