<?php
/**
 * Created W/30/05/2012
 * Updated M/26/02/2013
 * Version 7
 *
 * Copyright 2012-2013 | Fabrice Creuzot (luigifab) <code~luigifab~info>
 * https://redmine.luigifab.info/projects/magento/wiki/versioning
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

if (!method_exists($this, 'translate')) {
	require_once('./errors/versioning/processor.php');
	$this->overload = new Versioning_Processor();
}
else {
	$this->overload = $this;
}

?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo substr($_SESSION['lang'], 0, 2) ?>" lang="<?php echo substr($_SESSION['lang'], 0, 2) ?>">
<head>
	<title><?php echo $this->overload->translate('Oups!') ?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="Content-Script-Type" content="text/javascript" />
	<meta http-equiv="Content-Style-Type" content="text/css" />
	<meta http-equiv="Content-Language" content="<?php echo substr($_SESSION['lang'], 0, 2) ?>" />

	<link rel="stylesheet" type="text/css" charset="utf-8" media="screen" href="<?php echo $this->overload->getUrl('errors/versioning/css/styles.css') ?>" />
	<?php if ($this->overload->hasUserCssFile()): ?>
		<link rel="stylesheet" type="text/css" charset="utf-8" media="screen" href="<?php echo $this->overload->getUrl('errors/versioning/config/user.css') ?>" />
	<?php endif ?>

	<link rel="icon" type="image/x-icon" href="<?php echo $this->overload->getUrl('favicon.ico') ?>" />
</head>

<body>
	<?php require_once($contentTemplate) ?>

</body>
</html>