<?php
/**
 * Created W/30/05/2012
 * Updated S/21/03/2015
 * Version 19
 *
 * Copyright 2011-2016 | Fabrice Creuzot (luigifab) <code~luigifab~info>
 * https://redmine.luigifab.info/projects/magento/wiki/versioning
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

$lang = substr($this->getData('lang'), 0, 2);
$code = (string) $code;

?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $lang ?>" lang="<?php echo $lang ?>">
<head>
	<title><?php echo $this->getPageTitle() ?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="Content-Script-Type" content="text/javascript" />
	<meta http-equiv="Content-Style-Type" content="text/css" />
	<meta http-equiv="Content-Language" content="<?php echo $lang ?>" />
	<link rel="icon" type="image/x-icon" href="<?php echo $this->getUrl('favicon.ico') ?>" />
	<!--link rel="stylesheet" type="text/css" charset="utf-8" media="screen" href="<?php //echo $this->getUrl('config/my.css') ?>" /-->
	<!--script type="text/javascript" charset="utf-8" src="<?php //echo $this->getUrl('config/my.js') ?>"></script-->

<style type="text/css">
* { margin:0; padding:0; background-clip:padding-box; }
body { font:0.85em sans-serif; background-color:#DDD; overflow-y:scroll; }
[title] { border-bottom:none; }
div.box { margin:auto; width:28rem; padding:3em 2em; }
div.number { margin:0 0 0.4em -0.1em; font-size:4em; font-weight:bold; color:#CCC; }
div.number span {
	display:inline-block; margin-right:0.1em; width:1.3em; height:1.3em; line-height:135%; text-align:center;
	border-radius:50%; border-bottom:1px solid #CACACA; background-color:#EEE;
}
h1 { margin-bottom:1em; font-size:1.3em; font-weight:normal; }
p { margin:1em 0; font-size:0.85em; line-height:140%; }
@media screen and (max-width:33rem),(max-device-width:33rem) {
	div.box { margin:0 1em 1em; width:auto; }
}
</style>
<script type="text/javascript">
var count = 0, timer;
window.addEventListener('load', function () {
	if (document.getElementById('reload')) {
		count = parseInt(document.getElementById('reload').querySelector('span').innerHTML, 10) - 1;
		timer = window.setInterval(function () {
			if (count > 1)
				document.getElementById('reload').querySelector('span').innerHTML = count--;
		}, 1000);
		window.setTimeout(function () { location.reload(); }, count * 1000);
	}
}, false);
</script>
</head>

<body>
	<div class="box">
		<div class="number">
			<span><?php echo $code[0] ?></span><span><?php echo $code[1] ?></span><span><?php echo $code[2] ?></span>
		</div>
		<h1><?php echo $this->getTitle() ?></h1>
		<?php echo $this->getHtmlContent() ?>
		<?php echo $this->getHtmlReload() ?>
		<?php if (!is_null($this->getReportId())): ?>
			<p><?php echo $this->__('Error number: §', $this->getReportId()) ?></p>
		<?php endif ?>
	</div>
</body>
</html>